# Generated by Django 3.1.12 on 2021-07-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_auto_20210726_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
