# Generated by Django 3.1.12 on 2021-07-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, max_length=6),
        ),
    ]
